In [3]:
import pandas as pd
import ftfy
import sklearn

In [4]:
df = pd.read_excel("TRANSFORMED DATA.xlsx") #loading my transformed data

In [5]:
#loading every worksheets
df_Location = pd.read_excel("TRANSFORMED DATA.xlsx", sheet_name="customers location")
df_Payment_type = pd.read_excel("TRANSFORMED DATA.xlsx", sheet_name="payment type")
df_high_value_customer = pd.read_excel("TRANSFORMED DATA.xlsx", sheet_name="high value customer")
df_monthly_growth = pd.read_excel("TRANSFORMED DATA.xlsx", sheet_name="monthly growth")
df_number_of_orders = pd.read_excel("TRANSFORMED DATA.xlsx", sheet_name="number of orders")
df_product_category_revenue = pd.read_excel("TRANSFORMED DATA.xlsx", sheet_name="product category revenue")
df_high_revenue_low_sales = pd.read_excel("TRANSFORMED DATA.xlsx", sheet_name="high revenue low sales")
df_sales_over_time = pd.read_excel("TRANSFORMED DATA.xlsx", sheet_name="sales over time")
df_seller_performance = pd.read_excel("TRANSFORMED DATA.xlsx", sheet_name="seller's performance")

In [ ]:
# Adding ranking and percentages to the products revenue for visualisation and comparison
df_product_category_revenue["Revenue Rank"] = (
    df_product_category_revenue["revenue"]
    .rank(
        ascending=False,
        method="dense"
    )
)

total_revenue = (
    df_product_category_revenue["revenue"]
    .sum()
)


df_product_category_revenue["Revenue Contribution %"] = (
    df_product_category_revenue["revenue"]
    /
    total_revenue
    *100
)

In [39]:
#to see the revenue growth in percentage
df_product_category_revenue

            product_category_name     revenue
0                 Cama Mesa Banho  1712553.67
1                    Beleza Saude  1657373.12
2          Informatica Acessorios  1585330.45
3                Moveis Decoracao  1430176.39
4              Relogios Presentes  1429216.68
..                            ...         ...
69                       Pc Gamer     2174.43
70                Casa Conforto 2     1710.54
71              Cds Dvds Musicais     1199.43
72  Fashion Roupa Infanto Juvenil      785.67
73             Seguros E Servicos      324.51

[74 rows x 2 columns]

In [6]:
df_monthly_growth["Growth %"] = (
    df_monthly_growth["revenue"]
    .pct_change()
    *100
)
df_monthly_growth

   sales_month     revenue  growth_percentage     Growth %
0          NaN  9514694.05                NaN          NaN
1      2016-02      109.34            -100.00   -99.998851
2      2016-03      595.14             444.30   444.302177
3      2016-04    12050.88            1924.88  1924.881540
4      2016-05    10287.28             -14.63   -14.634616
5      2016-06     9398.61              -8.64    -8.638532
6      2016-07     8255.19             -12.17   -12.165842
7      2016-08     9716.13              17.70    17.697230
8      2016-09     4152.11             -57.27   -57.265804
9      2016-10     4675.10              12.60    12.595765
10     2017-01   249193.95            5230.24  5230.237856
11     2017-02   219536.57             -11.90   -11.901324
12     2017-03   225938.92               2.92     2.916302
13     2017-04   249212.23              10.30    10.300709
14     2017-05   240084.59              -3.66    -3.662597
15     2017-06   264132.26              10.02    10.016332
16     2017-07   224734.66             -14.92   -14.915861
17     2017-08   210156.34              -6.49    -6.486903
18     2017-09   218797.67               4.11     4.111858
19     2017-10   229821.23               5.04     5.038244
20     2017-11   240549.81               4.67     4.668228
21     2017-12   230513.01              -4.17    -4.172441
22     2018-01   279740.81              21.36    21.355758
23     2018-02   296857.70               6.12     6.118839
24     2018-03   303567.57               2.26     2.260298
25     2018-04   312947.95               3.09     3.090047
26     2018-05   308727.16              -1.35    -1.348719
27     2018-06   306723.45              -0.65    -0.649023
28     2018-07   320630.88               4.53     4.534192
29     2018-08   294892.40              -8.03    -8.027449
30     2018-09   315934.53               7.14     7.135528
31     2018-10   286333.69              -9.37    -9.369296
32     2018-11   311075.28               8.64     8.640824
33     2018-12   294835.63              -5.22    -5.220489

In [7]:
datasets = {
    "Location": df_Location,
    "Payment_type": df_Payment_type,
    "High_value_customer": df_high_value_customer,
    "Monthly_growth": df_monthly_growth,
    "Number_of_orders": df_number_of_orders,
    "Product_category_revenue": df_product_category_revenue,
    "High_revenue_low_sales": df_high_revenue_low_sales,
    "Sales_over_time": df_sales_over_time,
    "Seller_performance": df_seller_performance
}

In [ ]:
#checking the column names
for name, df in datasets.items():
    print(name)
    print(df.columns.tolist())
    print()

In [ ]:
#Removing the spaces in the column names
for name, df in datasets.items():
    df.columns = (
        df.columns
        .str.strip()
        .str.lower()
        .str.replace(" ", "_")
    )

In [ ]:
#cleaning the text columns
for name, df in datasets.items():

    text_columns = df.select_dtypes(
        include="object"
    ).columns

    for col in text_columns:
        df[col] = (
            df[col]
            .str.strip()
            .str.lower()
        )

In [ ]:
#fixing the texts with my ftfy library but first i will create a function to clean the text
def clean_text(value):
    if isinstance(value, str):
        value = ftfy.fix_text(value)
        value = value.strip()
    return value

In [ ]:
#now applying the fix to all my worksheets
for name, df in datasets.items():

    text_columns = df.select_dtypes(
        include="object"
    ).columns

    for col in text_columns:
        df[col] = df[col].apply(clean_text)

    print(f"{name} cleaned successfully")

In [ ]:
#checking for duplicates
for name, df in datasets.items():

    print(
        name,
        "duplicates:",
        df.duplicated().sum()
    )

In [1]:
df_Location

NameError: name 'df_Location' is not defined

In [ ]:

df_Location["city"] = (
    df_Location["city"]
    .apply(lambda x: ftfy.fix_text(x) if isinstance(x, str) else x)
)
df_Location["city"] = (
    df_Location["city"]
    .str.strip()
)

In [ ]:
df_Location["city"] = (
    df_Location["city"]
    .str.title()
)
df_Location

In [ ]:
def fix_encoding(text):
    if isinstance(text, str):
        try:
            return text.encode("latin1").decode("utf-8")
        except:
            return ftfy.fix_text(text)
    return text


df_Location["city"] = (
    df_Location["city"]
    .apply(fix_encoding)
)

In [ ]:
df_Location

In [ ]:
df_Location["city"] = (
    df_Location["city"]
    .str.replace("£", "", regex=False)
    .str.strip()
)

In [ ]:
df_Location